CREATE TABLE DMHR.REGION (
  REGION_ID INT NOT NULL,
  REGION_NAME VARCHAR(25) NULL,
  CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID)
);

CREATE UNIQUE INDEX INDEX33555566 ON DMHR.REGION (REGION_ID);

INSERT INTO
  DMHR.REGION (REGION_ID, REGION_NAME)
VALUES
  (1, '华北'),
  (2, '华东'),
  (3, '华南'),
  (4, '中南'),
  (5, '东北'),
  (6, '西北'),
  (7, '西南');

